version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: bridge_pdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aximilli1212
      POSTGRES_PASSWORD: aximilli1212
      POSTGRES_DB: bridge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
